// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcc429mg8DvpWWCZw1ANWbJO1sMZ73GnM',
    appId: '1:1094288950573:web:e382c8c83234c4fd72ffa4',
    messagingSenderId: '1094288950573',
    projectId: 'dementia-assist-d6d2c',
    authDomain: 'dementia-assist-d6d2c.firebaseapp.com',
    databaseURL: 'https://dementia-assist-d6d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dementia-assist-d6d2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JYxFuxEevgRfKP6LigGo4HW9PA-TLxs',
    appId: '1:1094288950573:android:5c81b11fe993ca8772ffa4',
    messagingSenderId: '1094288950573',
    projectId: 'dementia-assist-d6d2c',
    databaseURL: 'https://dementia-assist-d6d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dementia-assist-d6d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kdyb1zKPwfi9z2VM6oE0WqenDiy5-w4',
    appId: '1:1094288950573:ios:bd3e0ba145936fb772ffa4',
    messagingSenderId: '1094288950573',
    projectId: 'dementia-assist-d6d2c',
    databaseURL: 'https://dementia-assist-d6d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dementia-assist-d6d2c.firebasestorage.app',
    iosBundleId: 'com.example.dementiaAssistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kdyb1zKPwfi9z2VM6oE0WqenDiy5-w4',
    appId: '1:1094288950573:ios:bd3e0ba145936fb772ffa4',
    messagingSenderId: '1094288950573',
    projectId: 'dementia-assist-d6d2c',
    databaseURL: 'https://dementia-assist-d6d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dementia-assist-d6d2c.firebasestorage.app',
    iosBundleId: 'com.example.dementiaAssistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcc429mg8DvpWWCZw1ANWbJO1sMZ73GnM',
    appId: '1:1094288950573:web:fabebd8db39bfe3672ffa4',
    messagingSenderId: '1094288950573',
    projectId: 'dementia-assist-d6d2c',
    authDomain: 'dementia-assist-d6d2c.firebaseapp.com',
    databaseURL: 'https://dementia-assist-d6d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dementia-assist-d6d2c.firebasestorage.app',
  );
}
